### ISSUE TITLE
cannot find moz_bookmarks in places.sqlite

### ISSUE THREAD

**Issue by Geektrovert** [YAS-opensource/BookMan#1]
Shows `no such table: moz_bookmarks` when running the code.

**Comment by cinder-star** [comment]
In my system the error is shown as:
```shell
no such table: moz_bookmarks
```
What I think is you didn't declare any tables(schema) in the **db_handler.py** file @Geektrovert

**Comment by Geektrovert** [comment]
@SedativeHypnotics This is an already existing DB which contains data from the bookmarks of Firefox. you can find the schema [here](https://wiki.mozilla.org/images/0/08/Places.sqlite.schema.pdf).

**Comment by Geektrovert** [comment]
Note to self: I'm a fucking idiot who returned an empty path from the location finder
